name: Dani Martinez (dan1t0)
url: https://dan1t0.com
description: Welcome to my blog. Here you’ll find technical information and practical solutions for IT security. Happy Hacking

permalink: /:year/:month/:day/:title/
paginate: 5 

#gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

plugins:
  - jekyll-paginate
  - jekyll-watch
